Add VIP: VET Custodian Contract Standard
vechain/VIPs pull request #45
Opened 2023-08-01 07:55 UTC by laalaguer

This VIP proposes a standard library, `StakingModel.sol` to better assist smart contract development by offloading VTHO-related calculations into a separate smart contract. It aims to ease the logic burden and prevent deadlock of VTHO in smart contracts on VeChain.

2023-09-01 06:15 UTC, NecoSherry commented
### File `vips/VIP-VET-Custodian.md`

Required 3 approvals from @zzGHzz, @qianbin, @libotony, @mongelly, @asbertMa, @bacco1977, @nwbrettski, @vineet-codes, @BenMVeChain, @daithihearn

2023-09-06 07:58 UTC, zzGHzz approved these changes

2023-09-20 00:52 UTC, wayne-qian approved these changes

2023-09-20 00:58 UTC, qianbin approved these changes

2023-10-04 20:19 UTC, sebaseek requested changes
Hi, there is a typo in StakingModel.sol error definition

   ```
 function removeVTHO(address addr, uint256 amount) restrict(amount) internal {
        _update(addr);
        require(users[addr].energy >= uint104(amount), "insuffcient vtho");
        users[addr].energy -= uint104(amount);
    }

    function removeVET(address addr, uint256 amount) restrict(amount) internal {
        _update(addr);
        require(users[addr].balance >= uint104(amount), "insuffcient vet");
        users[addr].balance -= uint104(amount);
    }
```

" insuffcient " => "insufficient"

2023-12-18 22:13 UTC, darrenvechain approved these changes

2024-01-08 04:54 UTC, NecoSherry commented on vips/VIP-VET-Custodian.md
> +Title: VET Custodian Contract Standard
```suggestion
VIP: 240
Title: VET Custodian Contract Standard
```

2024-01-08 04:54 UTC, NecoSherry commented on vips/VIP-VET-Custodian.md
> +Status: Idea
```suggestion
Status: Draft
```

2024-01-09 03:23 UTC, libotony commented
@NecoSherry, I've made the necessary modifications to the files, including the VIP number. They are now ready for merging.

2024-01-09 10:38 UTC, sebaseek approved these changes

2024-01-10 03:06 UTC, merged