Add draft version of VIP-TokenRecovery
vechain/VIPs pull request #49
Opened 2023-08-30 18:40 UTC by VetMaik

This is a draft version of the VIP-TokenRecovery

2023-08-31 07:18 UTC, NecoSherry commented
Hi there! Thank you for submitting your proposal. Feel free to make adjustments to your pull request based on the community discussion. Once your proposal is prepared, please request review from the operation team (@NecoSherry).

2023-09-04 16:00 UTC, VetMaik commented
Based on feedback from Brettski, I made a start on the actual guides.
I also added two additional ideas I had that work very well with the guides.

1. With the release of the official vechain bridge, it would be great to be able to swap VET from different networks. Since other networks like BSC and Cronos have their own bridged VET, this would help our holders a lot. Instead of sending wrongly withdrawn VET back to the CEX, they can easily swap it to real VET from our official bridge.

2. I would like VeWorld to have custom derivation path support. Sync2 supports this since a few months and it is a game changer. It made my guides more easy to follow and a lot safer.

2023-09-18 18:50 UTC, VetMaik commented
Hi @NecoSherry ! I had some discussion with Brettski on Discourse and added one of the guides in this pull request!
I wonder what you think of this.

2023-10-04 19:45 UTC, sebaseek commented
Hi @VetMaik thanks for your contribution

just a chore text thing I saw in the following sentence: 

"Open Sync2 on your mobile device or computer and choose the import wallet option"

I would add quote symbol in the word import to express the desired CTA functionality

"Open Sync2 on your mobile device or computer and choose the 'import' wallet option"

Is there anything else you would like to add or we can proceed to review it completely

2023-10-05 06:45 UTC, VetMaik commented
@sebaseek I added a second article for Binance Smart Chain and added your feedback as well.
It's now ready to review.

2023-11-09 05:42 UTC, bacco1977 approved these changes
ok

2023-11-09 05:43 UTC, bacco1977 commented
I completed my review thanks @VetMaik 
If the rest of the team has some further comments I have none

2023-12-11 16:41 UTC, nwbrettski approved these changes
LGTM.

2023-12-11 16:43 UTC, nwbrettski commented
@NecoSherry can we progress to the next steps with this and close the VIP out. Thanks.

2023-12-14 13:51 UTC, VetMaik commented
@NecoSherry I made the requested changes and relocated/renamed the files.

2023-12-15 08:45 UTC, daithihearn requested changes

2023-12-15 08:45 UTC, daithihearn commented on assets/vip-230/articles/Sent VET on the VechainThor network to BSC Address.md
> +Did you sent your VET tokens to your Binance Smart Chain (BSC) address? This guide will help you retrieve them.
Typo. Change *sent* to *send*

2023-12-15 08:45 UTC, daithihearn commented on assets/vip-230/articles/Sent VET on the VechainThor network to Ethereum Address.md
> +Did you sent your VET tokens to your Ethereum address? This guide will help you retrieve them.
Typo. Change **sent** to **send**

2023-12-15 10:04 UTC, VetMaik commented on assets/vip-230/articles/Sent VET on the VechainThor network to Ethereum Address.md
> +Did you sent your VET tokens to your Ethereum address? This guide will help you retrieve them.
Thanks again!

2023-12-15 10:06 UTC, VetMaik reviewed
Thanks for finding!

2023-12-15 13:48 UTC, daithihearn approved these changes

2023-12-15 13:55 UTC, VetMaik reviewed
Done

2023-12-18 08:38 UTC, merged

2023-12-19 02:40 UTC, libotony commented
Hi @VetMaik, can you add links to the articles in file vip-230.md?

2024-06-15 07:03 UTC, Andredreyer1 commented
.

2024-06-15 07:04 UTC, Andredreyer1 reviewed
.

2024-06-15 07:05 UTC, Andredreyer1 commented
.

2024-06-15 07:05 UTC, Andredreyer1 commented
.