add VIP: ETH Shanghai Upgrade Specification
vechain/VIPs pull request #71
Opened 2024-01-25 10:44 UTC by libotony

2024-01-31 08:32 UTC, darrenvechain approved these changes

2024-04-18 15:24 UTC, daithihearn approved these changes

2024-04-26 09:09 UTC, nwbrettski approved these changes

2024-04-26 09:30 UTC, NecoSherry requested changes

2024-04-26 09:30 UTC, NecoSherry commented on vips/VIP-eth-shanghai-upgrade-specification.md
> +Title: ETH Shanghai Upgrade Specification
```suggestion
VIP: 242
Title: ETH Shanghai Upgrade Specification
```

2024-04-26 09:30 UTC, NecoSherry commented on vips/VIP-eth-shanghai-upgrade-specification.md
> +Title: ETH Shanghai Upgrade Specification
VIP number assigned. Please rename the file to `VIP-242.md`.

2024-04-26 10:22 UTC, NecoSherry approved these changes

2024-04-26 10:23 UTC, merged